[pytest]
testpaths = tests
pythonpath = .
addopts =
    --browser chromium
    --tracing retain-on-failure
    --screenshot only-on-failure
    --video retain-on-failure
timeout = 120

[pytest-playwright]
base_url = https://evo.dev.theysaid.io
