"""
Thread 3 — Answer Survey Flow.

Answer selection is intentionally arbitrary/best-effort — AI-generated surveys have
no single "correct" response. The goal is verifying the respondent flow completes
without breaking, not validating survey logic.

Requires `output/project-link.txt` from Thread 1 (`test_create_project_flow`).
That file stores one theysaid.io survey URL per line.
Run: pytest tests/test_create_project.py && pytest tests/test_answer_survey.py
"""

import re

import bootstrap  # noqa: F401

import pytest
from playwright.sync_api import Browser, Locator, Page, expect

from config import DEFAULT_TIMEOUT, OUTPUT_DIR
from helpers.project_link import load_project_link
from helpers.page_waits import wait_for_page_load
from locators.survey_locators import SurveyLocators

# Arbitrary placeholder — no correct answer required for AI-graded surveys.
FREE_TEXT_RESPONSE = "This is a test response generated by automated QA."
MAX_SURVEY_ITERATIONS = 50
NAV_BUTTON_PATTERN = re.compile(r"^(Continue|Next|Submit|Finish|Start)$", re.I)


def _load_project_link() -> str:
    """Step 1: Read project link written by Thread 1."""
    return load_project_link()


def _is_navigation_button(locator: Locator) -> bool:
    try:
        if not locator.is_visible():
            return False
        label = (locator.get_attribute("aria-label") or locator.inner_text() or "").strip()
        return bool(NAV_BUTTON_PATTERN.match(label))
    except Exception:
        return False


def _first_visible(locator: Locator) -> Locator | None:
    for index in range(locator.count()):
        candidate = locator.nth(index)
        if candidate.is_visible():
            return candidate
    return None


def _is_survey_complete(page: Page, survey: SurveyLocators) -> bool:
    indicator = survey.completion_indicator()
    if indicator.count() == 0:
        return False
    try:
        return indicator.first.is_visible()
    except Exception:
        return False


def _dom_snippet(page: Page, max_length: int = 500) -> str:
    try:
        text = page.locator("body").inner_text(timeout=5_000)
        collapsed = " ".join(text.split())
        return collapsed[:max_length]
    except Exception as exc:
        return f"<unable to read DOM: {exc}>"


def _has_answerable_input(page: Page, survey: SurveyLocators) -> bool:
    if _first_visible(survey.visible_radios()) is not None:
        return True
    for index in range(survey.visible_checkboxes().count()):
        checkbox = survey.visible_checkboxes().nth(index)
        if checkbox.is_visible() and not _is_navigation_button(checkbox):
            return True
    if _first_visible(page.get_by_role("option")) is not None:
        return True
    if _first_visible(survey.visible_textareas()) is not None:
        return True
    for index in range(survey.visible_textboxes().count()):
        textbox = survey.visible_textboxes().nth(index)
        if textbox.is_visible() and textbox.is_editable():
            return True
    if _first_visible(survey.scale_buttons()) is not None:
        return True

    for index in range(page.get_by_role("button").count()):
        button = page.get_by_role("button").nth(index)
        if button.is_visible() and not _is_navigation_button(button):
            return True

    return False


def _answer_multiple_choice(page: Page, survey: SurveyLocators) -> bool:
    """Arbitrary choice — first visible option; no specific answer required."""
    radio = _first_visible(survey.visible_radios())
    if radio is not None:
        radio.click()
        return True

    for index in range(survey.visible_checkboxes().count()):
        checkbox = survey.visible_checkboxes().nth(index)
        if checkbox.is_visible() and not _is_navigation_button(checkbox):
            checkbox.check()
            return True

    option = _first_visible(page.get_by_role("option"))
    if option is not None:
        option.click()
        return True

    for index in range(page.get_by_role("button").count()):
        button = page.get_by_role("button").nth(index)
        if button.is_visible() and not _is_navigation_button(button):
            button.click()
            return True

    return False


def _answer_free_text(survey: SurveyLocators) -> bool:
    textarea = _first_visible(survey.visible_textareas())
    if textarea is not None:
        textarea.fill(FREE_TEXT_RESPONSE)
        return True

    for index in range(survey.visible_textboxes().count()):
        textbox = survey.visible_textboxes().nth(index)
        if textbox.is_visible() and textbox.is_editable():
            textbox.fill(FREE_TEXT_RESPONSE)
            return True

    return False


def _answer_rating_scale(survey: SurveyLocators) -> bool:
    scale = survey.scale_buttons()
    visible: list[Locator] = []
    for index in range(scale.count()):
        button = scale.nth(index)
        if button.is_visible():
            visible.append(button)

    if not visible:
        return False

    middle = visible[len(visible) // 2]
    middle.click()
    return True


def _answer_current_question(page: Page, survey: SurveyLocators) -> bool:
    if _answer_multiple_choice(page, survey):
        return True
    if _answer_free_text(survey):
        return True
    if _answer_rating_scale(survey):
        return True
    return False


def _click_continue_if_present(survey: SurveyLocators) -> bool:
    button = _first_visible(survey.continue_button())
    if button is None:
        return False
    button.click()
    return True


def _wait_for_next_step(page: Page, survey: SurveyLocators) -> None:
    if _is_survey_complete(page, survey):
        return

    wait_for_page_load(page)
    survey.continue_button().or_(survey.visible_radios().first).or_(
        survey.visible_textboxes().first
    ).or_(survey.completion_indicator()).first.wait_for(state="visible", timeout=DEFAULT_TIMEOUT)


@pytest.fixture
def respondent_page(browser: Browser, browser_context_args: dict) -> Page:
    """Step 2: Fresh unauthenticated context — simulates a survey respondent."""
    context = browser.new_context(**browser_context_args)
    page = context.new_page()
    page.set_default_timeout(DEFAULT_TIMEOUT)
    yield page
    context.close()


def test_answer_survey_flow(respondent_page: Page) -> None:
    page = respondent_page
    survey = SurveyLocators(page)
    screenshot_path = OUTPUT_DIR / "survey-completion.png"

    # Step 1: Load project link from Thread 1 output
    project_link = _load_project_link()

    # Step 2–3: Navigate in unauthenticated context
    page.goto(project_link, wait_until="domcontentloaded")
    wait_for_page_load(page)

    if _is_survey_complete(page, survey):
        expect(survey.completion_indicator().first).to_be_visible(timeout=DEFAULT_TIMEOUT)
        page.screenshot(path=str(screenshot_path), full_page=True)
        return

    # Step 4: Answer questions until completion or safety limit
    for iteration in range(1, MAX_SURVEY_ITERATIONS + 1):
        if _is_survey_complete(page, survey):
            break

        if _has_answerable_input(page, survey):
            if not _answer_current_question(page, survey):
                page.screenshot(path=str(screenshot_path), full_page=True)
                pytest.fail(
                    f"Survey stuck on iteration {iteration}: answerable input detected "
                    f"but could not be filled. DOM snippet: {_dom_snippet(page)}"
                )

        if _is_survey_complete(page, survey):
            break

        if not _click_continue_if_present(survey):
            if _is_survey_complete(page, survey):
                break
            page.screenshot(path=str(screenshot_path), full_page=True)
            pytest.fail(
                f"Survey stuck on iteration {iteration}: no Continue/Next/Submit/Finish "
                f"button and survey not complete. DOM snippet: {_dom_snippet(page)}"
            )

        _wait_for_next_step(page, survey)
    else:
        page.screenshot(path=str(screenshot_path), full_page=True)
        pytest.fail(
            f"Survey did not complete within {MAX_SURVEY_ITERATIONS} iterations. "
            f"DOM snippet: {_dom_snippet(page)}"
        )

    # Step 5: Assert completion indicator is visible
    expect(survey.completion_indicator().first).to_be_visible(timeout=DEFAULT_TIMEOUT)
    page.screenshot(path=str(screenshot_path), full_page=True)
